spring.application.name=MovieCatalogAPI

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/movie_catalog
spring.datasource.username=root
spring.datasource.password=Nandu@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

app.name=Movie Catalog Service
app.version=1.0
catalog.max-genres-per-movie=5
catalog.default-rating=5.0